services:
  app_db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: clp_db
      POSTGRES_USER: clp_user
      POSTGRES_PASSWORD: clp_password
    volumes:
      - app_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 2s
      retries: 15
    ports:
      - "5432:5432"
    networks:
      - local_network
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    volumes:
      - keycloak_data:/opt/keycloak/data/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "7080", "--https-port", "7443" ]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge
volumes:
  app_db_data:
  keycloak_data: